services:
  zpodweb:
    container_name: zpodweb-ui
    build: .
    image: zpodfactory/zpodweb-ui:latest
    ports:
      - "${ZPODWEB_DEFAULT_UI_PORT:-8500}:80"
    env_file:
      - .env
    restart: unless-stopped
